template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  Thank you to $CONTRIBUTORS
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
autolabeler:
  - label: 'feature'
    title:
      - '/feat/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'chore'
    title:
      - '/chore/i'
